version: '3.7'

services:
  mypostgres:
    image: postgres:latest
    container_name: mypostgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  myredis:
    image: redis:latest
    container_name: myredis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - app-network

  book-store:
    build: 
      context: .
      dockerfile: Dockerfile
    image: sieunhantanbao/book-store:latest
    container_name: book-store
    restart: unless-stopped
    environment:
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - UPLOAD_FOLDER=${UPLOAD_FOLDER}
      - ALLOWED_EXTENSIONS=${ALLOWED_EXTENSIONS}
      - DB_ENGINE=${DB_ENGINE}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DEFAULT_PASSWORD=${DEFAULT_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
    depends_on:
      - mypostgres
      - migration
      - myredis
    ports:
      - "5001:5000"
    networks:
      - app-network
    command: flask run --host 0.0.0.0

  migration:
    build: 
      context: .
      dockerfile: Dockerfile
    image: sieunhantanbao/book-store-migration:latest
    environment:
      - DB_ENGINE=${DB_ENGINE}
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - WAIT_HOSTS=mypostgres:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    entrypoint: 
            - /bin/bash
            - -c
            - |
                /app/wait && \
                alembic upgrade head
    depends_on:
      - mypostgres
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data:
