"""Add new column

Revision ID: 74c0343d846e
Revises: 
Create Date: 2024-01-10 15:01:22.827360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c0343d846e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.add_column('book', sa.Column('is_featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'is_featured')
    op.drop_column('book', 'sort_order')
    # ### end Alembic commands ###
