"""create book table

Revision ID: b58635ce7d96
Revises: 7de2c164117f
Create Date: 2024-03-17 13:51:33.177029

"""
from typing import Sequence, Union
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from uuid import UUID

# revision identifiers, used by Alembic.
revision: str = 'b58635ce7d96'
down_revision: Union[str, None] = '7de2c164117f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    book_table = op.create_table("books",
                                 sa.Column("id", sa.UUID, nullable=False, primary_key=True),
                                 sa.Column('category_id', sa.UUID, nullable=False),
                                 sa.Column('title', sa.String, nullable=False),
                                 sa.Column('slug', sa.String, nullable=False),
                                 sa.Column('short_description', sa.String),
                                 sa.Column('description', sa.String),
                                 sa.Column('price', sa.Float, nullable=False),
                                 sa.Column('isbn', sa.String, nullable=False),
                                 sa.Column('author', sa.String, nullable=False),
                                 sa.Column('publisher', sa.String),
                                 sa.Column('publish_date', sa.DateTime),
                                 sa.Column('pages', sa.Integer),
                                 sa.Column('dimensions', sa.String),
                                 sa.Column('language', sa.String),
                                 sa.Column('thumbnail_url', sa.String),
                                 sa.Column('sort_order', sa.Integer),
                                 sa.Column('is_featured', sa.Boolean, nullable=False,default=False),
                                 sa.Column('is_published', sa.Boolean, nullable=False, default=False),
                                 sa.Column('created_at', sa.DateTime, nullable=False, default=datetime.now()),
                                 sa.Column('updated_at', sa.DateTime))
    op.create_foreign_key('fk_book_category', 'books', 'categories', ['category_id'], ['id'])

    book_data = [
            {
                "id": UUID("5506433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("D967C683-7A87-4583-A849-4E8DE8A190E2"),
                "title":"10 Vạn Câu Hỏi Vì Sao - Khoa Học Quanh Ta 1",
                "slug": "10-van-cau-hoi-vi-sao-khoa-hoc-quanh-ta-1",
                "short_description": "Tuổi thơ là khoảng thời gian đẹp nhất trong cuộc đời mỗi người. Ở lứa tuổi này luôn tràn đầy hy vọng, ước mơ, cùng những ngây thơ trong sáng buổi ban đầu. Đứng trước thế giới với bao điều kỳ diệu, mang trong mình sự tò mò, khát vọng tìm hiểu, câu nói thường thấy nhất ở trẻ là 'Vì sao?'.",
                "price": 2,
                "isbn": "8935212340427",
                "author": "Tôn Nguyên Vĩ",
                "publisher": "NXB Thanh Niên",
                "publish_date": "2024-01-01 00:00:00.000000",
                "pages": 139,
                "dimensions": "14.5 x 20.5 cm",
                "language": "Tiếng Việt",
                "sort_order": 0,
                "is_featured": True,
                "is_published": True,
                "description": "<p>Discover the wonders of the cosmos in this beautifully illustrated book.</p>"
            },
            {
                "id": UUID("5906433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("C4028EA3-29F3-4E57-BBE6-17EE8A172564"),
                "title":"The Hidden Universe",
                "slug": "the-hidden-universe",
                "short_description": "Explore the mysteries of the universe in this captivating book.",
                "price": 25,
                "isbn": "978-1234567890",
                "author": "Astronomy Guru",
                "publisher": "Stellar Publications",
                "publish_date": "2022-01-10 00:00:00.000000",
                "pages": 300,
                "dimensions": "50 x 210 x 20",
                "language": "English",
                "sort_order": 0,
                "is_featured": True,
                "is_published": True,
                "description": "<p>Discover the wonders of the cosmos in this beautifully illustrated book.</p>                                                                                                                                        "
            },
            {
                "id": UUID("5D06433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("D62FD3DD-D186-45B8-B0BB-188BE89E5430"),
                "title":"Beyond the Horizon",
                "slug": "beyond-the-horizon",
                "short_description": "Embark on an epic journey beyond the horizon with this thrilling adventure.",
                "price": 50,
                "isbn": "123-0-56789-012-3",
                "author": "Adventure Author",
                "publisher": "Epic Adventures Publishing",
                "publish_date": "2021-09-05 00:00:00.000000",
                "pages": 450,
                "dimensions": "80 x 240 x 30",
                "language": "English",
                "sort_order": 0,
                "is_featured": False,
                "is_published": True,
                "description": "<p>Join our heroes as they navigate uncharted territories and face unimaginable challenges.</p>                                                                                                                                        "
            },
            {
                "id": UUID("6106433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("D967C683-7A87-4583-A849-4E8DE8A190E2"),
                "title":"Eternal Love",
                "slug": "eternal-love",
                "short_description": "A timeless tale of love and sacrifice that will tug at your heartstrings.",
                "price": 30,
                "isbn": "978-9876543210",
                "author": "Romance Novelist",
                "publisher": "Love Stories Co.",
                "publish_date": "2021-05-20 00:00:00.000000",
                "pages": 200,
                "dimensions": "20 x 180 x 15",
                "language": "English",
                "sort_order": 0,
                "is_featured": True,
                "is_published": True,
                "description": "<p>Follow the poignant journey of two souls entwined in an eternal love story.</p>                                                                                                                                        "
            },
            {
                "id": UUID("6506433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("3DC81F23-1691-437C-AB95-19E77781A19A"),
                "title":"The Code Breaker",
                "slug": "the-code-breaker",
                "short_description": "Unravel the secrets of genetics with the fascinating story of a code-breaking scientist.",
                "price": 40,
                "isbn": "978-1541672600",
                "author": "Genomic Pioneer",
                "publisher": "Scientific Press",
                "publish_date": "2021-11-15 00:00:00.000000",
                "pages": 500,
                "dimensions": "60 x 230 x 25",
                "language": "English",
                "sort_order": 0,
                "is_featured": True,
                "is_published": True,
                "description": "<p>Explore the groundbreaking work of geneticists and their quest to decode the mysteries of life.</p>                                                                                                                                        "
            },
            {
                "id": UUID("6906433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("7328775F-F4EB-49C1-9CC3-B344CC6C7EA3"),
                "title":"Culinary Delights",
                "slug": "culinary-delights",
                "short_description": "Savor the flavors of a culinary journey through this gastronomic masterpiece.",
                "price": 75,
                "isbn": "012-3-45678-900-2",
                "author": "Master Chef",
                "publisher": "Gourmet Books Ltd.",
                "publish_date": "2022-03-08 00:00:00.000000",
                "pages": 350,
                "dimensions": "00 x 250 x 40",
                "language": "English",
                "sort_order": 0,
                "is_featured": True,
                "is_published": True,
                "description": "<p>Indulge in a collection of mouthwatering recipes and culinary adventures from around the world.</p>                                                                                                                                        "
            },
            {
                "id": UUID("6D06433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("C4028EA3-29F3-4E57-BBE6-17EE8A172564"),
                "title":"Infinite Possibilities",
                "slug": "infinite-possibilities",
                "short_description": "Expand your mind with this thought-provoking exploration of infinite possibilities.",
                "price": 60,
                "isbn": "978-0321775658",
                "author": "Philosophy Scholar",
                "publisher": "Mind-Expanding Books Co.",
                "publish_date": "2021-07-12 00:00:00.000000",
                "pages": 800,
                "dimensions": "70 x 220 x 50",
                "language": "English",
                "sort_order": 0,
                "is_featured": True,
                "is_published": True,
                "description": "<p>Dive into the realm of infinite possibilities and challenge your understanding of reality.</p>                                                                                                                                        "
            },
            {
                "id": UUID("7106433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("3DC81F23-1691-437C-AB95-19E77781A19A"),
                "title":"Secrets of the Ancient World",
                "slug": "secrets-of-the-ancient-world",
                "short_description": "Uncover the hidden secrets of ancient civilizations in this historical masterpiece.",
                "price": 55,
                "isbn": "978-0307277719",
                "author": "Archaeology Expert",
                "publisher": "History Press",
                "publish_date": "2022-02-28 00:00:00.000000",
                "pages": 600,
                "dimensions": "90 x 260 x 35",
                "language": "English",
                "sort_order": 0,
                "is_featured": False,
                "is_published": True,
                "description": "<p>Journey through time as we unravel the mysteries of ancient civilizations and their incredible legacies.</p>                                                                                                                                        "
            },
            {
                "id": UUID("7506433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("D62FD3DD-D186-45B8-B0BB-188BE89E5430"),
                "title":"Tech Titans",
                "slug": "tech-titans",
                "short_description": "Explore the lives and innovations of tech titans who shaped the digital age.",
                "price": 45,
                "isbn": "978-0066620424",
                "author": "Tech Historian",
                "publisher": "Innovative Books Inc.",
                "publish_date": "2021-10-03 00:00:00.000000",
                "pages": 400,
                "dimensions": "55 x 200 x 30",
                "language": "English",
                "sort_order": 0,
                "is_featured": True,
                "is_published": True,
                "description": "<p>Discover the stories behind the visionaries who revolutionized the world of technology.</p>                                                                                                                                        "
            },
            {
                "id": UUID("7906433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("D967C683-7A87-4583-A849-4E8DE8A190E2"),
                "title":"The Art of Mindfulness",
                "slug": "the-art-of-mindfulness",
                "short_description": "Achieve inner peace and tranquility with the timeless wisdom of mindfulness.",
                "price": 35,
                "isbn": "978-0749953089",
                "author": "Mindfulness Guru",
                "publisher": "Zen Publications",
                "publish_date": "2021-06-15 00:00:00.000000",
                "pages": 250,
                "dimensions": "30 x 190 x 20",
                "language": "English",
                "sort_order": 0,
                "is_featured": True,
                "is_published": True,
                "description": "<p>Learn the art of mindfulness and cultivate a peaceful and harmonious life.</p>                                                                                                                                        "
            },
            {
                "id": UUID("7D06433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("C4028EA3-29F3-4E57-BBE6-17EE8A172564"),
                "title":"Quantum Leap",
                "slug": "quantum-leap",
                "short_description": "Take a quantum leap into the fascinating world of quantum mechanics and its mysteries.",
                "price": 80,
                "isbn": "978-0553381323",
                "author": "Quantum Physicist",
                "publisher": "Quantum Books Co.",
                "publish_date": "2022-04-25 00:00:00.000000",
                "pages": 700,
                "dimensions": "75 x 230 x 45",
                "language": "English",
                "sort_order": 0,
                "is_featured": False,
                "is_published": True,
                "description": "<p>Explore the mind-bending principles of quantum mechanics and their profound implications on reality.</p>                                                                    "
            },
            {
                "id": UUID("8106433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("7328775F-F4EB-49C1-9CC3-B344CC6C7EA3"),
                "title":"The Elements of Art",
                "slug": "the-elements-of-art",
                "short_description": "Unlock the secrets of artistic expression with this comprehensive guide to the elements of art.",
                "price": 20,
                "isbn": "978-0500202975",
                "author": "Art Educator",
                "publisher": "Creative Publishing House",
                "publish_date": "2021-09-30 00:00:00.000000",
                "pages": 150,
                "dimensions": "10 x 160 x 15",
                "language": "English",
                "sort_order": 0,
                "is_featured": True,
                "is_published": True,
                "description": "<p>Discover the fundamental elements of art and enhance your creative journey with practical insights and exercises.</p>                                                                    "
            },
            {
                "id": UUID("8506433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("D62FD3DD-D186-45B8-B0BB-188BE89E5430"),
                "title":"The Culmination",
                "slug": "the-culmination",
                "short_description": "Witness the culmination of a gripping saga in this thrilling conclusion.",
                "price": 65,
                "isbn": "123-4-56789-012-3",
                "author": "Epic Fantasy Author",
                "publisher": "Fantasy Realms Publishing",
                "publish_date": "2021-12-20 00:00:00.000000",
                "pages": 550,
                "dimensions": "85 x 240 x 40",
                "language": "English",
                "sort_order": 0,
                "is_featured": True,
                "is_published": True,
                "description": "<p>As the story reaches its climax, prepare for an epic conclusion that will leave you on the edge of your seat.</p>                                                                    "
            },
            {
                "id": UUID("8906433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("7328775F-F4EB-49C1-9CC3-B344CC6C7EA3"),
                "title":"Gastronomic Adventures",
                "slug": "gastronomic-adventures",
                "short_description": "Embark on a culinary journey around the world with this delightful gastronomic adventure.",
                "price": 55,
                "isbn": "978-0062458262",
                "author": "Food Enthusiast",
                "publisher": "Culinary Delights Press",
                "publish_date": "2022-01-18 00:00:00.000000",
                "pages": 400,
                "dimensions": "60 x 210 x 30",
                "language": "English",
                "sort_order": 0,
                "is_featured": False,
                "is_published": True,
                "description": "<p>Join our gastronomic explorers as they uncover the flavors and traditions of diverse cuisines across the globe.</p>                                                                                                                                        "
            },
            {
                "id": UUID("8D06433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("C4028EA3-29F3-4E57-BBE6-17EE8A172564"),
                "title":"The Quantum Code",
                "slug": "the-quantum-code",
                "short_description": "Crack the quantum code and unlock the secrets of the universe with this mind-bending exploration.",
                "price": 70,
                "isbn": "978-0307948787",
                "author": "Quantum Explorer",
                "publisher": "Cosmic Insights Publishing",
                "publish_date": "2022-03-10 00:00:00.000000",
                "pages": 600,
                "dimensions": "70 x 220 x 40",
                "language": "English",
                "sort_order": 0,
                "is_featured": True,
                "is_published": True,
                "description": "<p>Join our intrepid explorers as they decipher the quantum code and delve into the mysteries of the cosmos.</p>                                                                "
            },
            {
                "id": UUID("9106433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("D967C683-7A87-4583-A849-4E8DE8A190E2"),
                "title":"Epic Love Stories",
                "slug": "epic-love-stories",
                "short_description": "Experience epic love stories that transcend time and space in this enchanting collection.",
                "price": 40,
                "isbn": "978-0062458255",
                "author": "Romance Maestro",
                "publisher": "Timeless Romance Books",
                "publish_date": "2021-07-05 00:00:00.000000",
                "pages": 300,
                "dimensions": "40 x 190 x 25",
                "language": "English",
                "sort_order": 0,
                "is_featured": False,
                "is_published": True,
                "description": "<p>Immerse yourself in timeless tales of love that defy the boundaries of reality and capture the essence of true romance.</p>                                                                    "
            },
            {
                "id": UUID("9506433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("3DC81F23-1691-437C-AB95-19E77781A19A"),
                "title":"The Renaissance",
                "slug": "the-renaissance",
                "short_description": "Discover the artistic and cultural rebirth of the Renaissance era in this captivating journey.",
                "price": 45,
                "isbn": "978-0192801630",
                "author": "Renaissance Scholar",
                "publisher": "Enlightenment Press",
                "publish_date": "2021-11-01 00:00:00.000000",
                "pages": 400,
                "dimensions": "70 x 230 x 35",
                "language": "English",
                "sort_order": 0,
                "is_featured": True,
                "is_published": True,
                "description": "<p>Explore the rich tapestry of the Renaissance period and the profound impact it had on art, science, and society.</p>                                                                    "
            },
            {
                "id": UUID("9906433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("D62FD3DD-D186-45B8-B0BB-188BE89E5430"),
                "title":"Uncharted Territories",
                "slug": "uncharted-territories",
                "short_description": "Embark on a perilous journey into uncharted territories with this gripping adventure.",
                "price": 55,
                "isbn": "978-0345331359",
                "author": "Adventure Explorer",
                "publisher": "Discovery Publications",
                "publish_date": "2021-08-15 00:00:00.000000",
                "pages": 500,
                "dimensions": "80 x 240 x 40",
                "language": "English",
                "sort_order": 0,
                "is_featured": True,
                "is_published": True,
                "description": "<p>Join our brave adventurers as they navigate treacherous landscapes and face the unknown in their quest for discovery.</p>                                                                    "
            },
            {
                "id": UUID("9D06433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("C4028EA3-29F3-4E57-BBE6-17EE8A172564"),
                "title":"The Science of Happiness",
                "slug": "the-science-of-happiness",
                "short_description": "Unlock the secrets to a fulfilling life with the science-backed principles of happiness.",
                "price": 30,
                "isbn": "978-0143114956",
                "author": "Happiness Expert",
                "publisher": "Joyful Living Books",
                "publish_date": "2021-10-22 00:00:00.000000",
                "pages": 250,
                "dimensions": "40 x 200 x 25",
                "language": "English",
                "sort_order": 0,
                "is_featured": True,
                "is_published": True,
                "description": "<p>Delve into the fascinating world of positive psychology and discover the keys to lasting happiness and well-being.</p>                                                                    "
            },
            {
                "id": UUID("A106433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("3DC81F23-1691-437C-AB95-19E77781A19A"),
                "title":"Mysteries of the Deep",
                "slug": "mysteries-of-the-deep",
                "short_description": "Plunge into the mysteries of the deep sea with this captivating exploration of marine wonders.",
                "price": 50,
                "isbn": "978-1426206436",
                "author": "Marine Biologist",
                "publisher": "Oceanic Press",
                "publish_date": "2022-02-12 00:00:00.000000",
                "pages": 450,
                "dimensions": "60 x 210 x 35",
                "language": "English",
                "sort_order": 0,
                "is_featured": True,
                "is_published": True,
                "description": "<p>Embark on an underwater odyssey and uncover the secrets of the deep sea, from vibrant coral reefs to elusive sea creatures.</p>                                                                    "
            },
            {
                "id": UUID("A506433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("7328775F-F4EB-49C1-9CC3-B344CC6C7EA3"),
                "title":"The Art of War",
                "slug": "the-art-of-war",
                "short_description": "Master the timeless strategies of warfare with this classic guide to the art of war.",
                "price": 35,
                "isbn": "978-0195014761",
                "author": "Military Strategist",
                "publisher": "Warfare Publications",
                "publish_date": "2021-09-18 00:00:00.000000",
                "pages": 300,
                "dimensions": "50 x 200 x 30",
                "language": "English",
                "sort_order": 0,
                "is_featured": True,
                "is_published": True,
                "description": "<p>Learn the strategic principles of warfare and gain insights into the art of leadership and decision-making.</p>                                                                    "
            },
            {
                "id": UUID("A906433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("C4028EA3-29F3-4E57-BBE6-17EE8A172564"),
                "title":"Into the Unknown",
                "slug": "into-the-unknown",
                "short_description": "Embark on a journey into the unknown with this mesmerizing exploration of the cosmos.",
                "price": 65,
                "isbn": "978-0521427081",
                "author": "Astrophysicist",
                "publisher": "Cosmic Journeys Publishing",
                "publish_date": "2021-12-08 00:00:00.000000",
                "pages": 600,
                "dimensions": "70 x 230 x 40",
                "language": "English",
                "sort_order": 0,
                "is_featured": True,
                "is_published": True,
                "description": "<p>Experience the wonders of the universe as our explorers venture into the vastness of space, encountering celestial phenomena and cosmic mysteries.</p>                                                                    "
            },
            {
                "id": UUID("AD06433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("D62FD3DD-D186-45B8-B0BB-188BE89E5430"),
                "title":"Enchanted Realms",
                "slug": "enchanted-realms",
                "short_description": "Step into enchanting realms of magic and wonder with this spellbinding fantasy adventure.",
                "price": 55,
                "isbn": "978-0061120084",
                "author": "Fantasy Maestro",
                "publisher": "Mythical Realms Publishing",
                "publish_date": "2021-08-05 00:00:00.000000",
                "pages": 500,
                "dimensions": "80 x 240 x 35",
                "language": "English",
                "sort_order": 0,
                "is_featured": False,
                "is_published": True,
                "description": "<p>Join our heroes as they embark on a quest through enchanted lands, encountering mythical creatures and facing magical challenges.</p>                                                                    "
            },
            {
                "id": UUID("B106433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("7328775F-F4EB-49C1-9CC3-B344CC6C7EA3"),
                "title":"The Culinary Explorer",
                "slug": "the-culinary-explorer",
                "short_description": "Embark on a culinary journey around the world with this delightful gastronomic adventure.",
                "price": 45,
                "isbn": "978-0743272459",
                "author": "Culinary Explorer",
                "publisher": "Global Cuisine Books",
                "publish_date": "2022-01-28 00:00:00.000000",
                "pages": 400,
                "dimensions": "60 x 210 x 30",
                "language": "English",
                "sort_order": 0,
                "is_featured": True,
                "is_published": True,
                "description": "<p>Join our culinary explorer as they discover the flavors and traditions of diverse cuisines across the globe.</p>                                                                    "
            },
            {
                "id": UUID("B506433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("C4028EA3-29F3-4E57-BBE6-17EE8A172564"),
                "title":"The Quantum Enigma",
                "slug": "the-quantum-enigma",
                "short_description": "Dive into the quantum enigma and unravel the mysteries of the subatomic world.",
                "price": 70,
                "isbn": "978-0307381678",
                "author": "Quantum Theorist",
                "publisher": "Quantum Insights Publishing",
                "publish_date": "2022-03-20 00:00:00.000000",
                "pages": 600,
                "dimensions": "75 x 230 x 45",
                "language": "English",
                "sort_order": 0,
                "is_featured": True,
                "is_published": True,
                "description": "<p>Explore the mind-bending phenomena of quantum physics and their implications on our understanding of reality.</p>                        "
            },
            {
                "id": UUID("B906433E-F36B-1410-922A-00CC96E21CB5"),
                "category_id": UUID("D967C683-7A87-4583-A849-4E8DE8A190E2"),
                "title":"Love Beyond Time",
                "slug": "love-beyond-time",
                "short_description": "Experience love that transcends time in this heartwarming collection of timeless romance tales.",
                "price": 40,
                "isbn": "978-0062458255",
                "author": "Romance Visionary",
                "publisher": "Timeless Romance Books",
                "publish_date": "2021-06-30 00:00:00.000000",
                "pages": 300,
                "dimensions": "40 x 190 x 25",
                "language": "English",
                "sort_order": 0,
                "is_featured": False,
                "is_published": True,
                "description": "<p>Immerse yourself in stories of love that endure through the ages, defying the boundaries of time itself.</p>"
            }                         
    ]
    
    op.bulk_insert(book_table, book_data)
    
def downgrade() -> None:
    op.drop_table("books")
    